--
-- 由SQLiteStudio v3.3.0 产生的文件 周一 6月 28 13:06:47 2021
--
-- 文本编码：System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- 表：Car
CREATE TABLE Car (AutoNo INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, PlateNo VARCHAR UNIQUE NOT NULL, VehicleWeight VARCHAR, CarOwner INTEGER REFERENCES Customer (Id) ON UPDATE CASCADE, Comment VARCHAR, Valid BOOLEAN DEFAULT (1));

-- 表：CarLabel
CREATE TABLE CarLabel (AutoNo INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, LabelNo VARCHAR UNIQUE NOT NULL, PlateNo VARCHAR REFERENCES Car (PlateNo) ON UPDATE CASCADE);

-- 表：Customer
CREATE TABLE Customer (Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, Num VARCHAR NOT NULL UNIQUE, Name VARCHAR NOT NULL UNIQUE, Type VARCHAR REFERENCES SysField (FieldValue) ON UPDATE CASCADE, Manager VARCHAR, Phone VARCHAR, Comment VARCHAR, Valid BOOLEAN DEFAULT (1));

-- 表：Goods
CREATE TABLE Goods (Id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, Num VARCHAR NOT NULL UNIQUE, Name VARCHAR NOT NULL UNIQUE, Type VARCHAR REFERENCES SysField (FieldValue) ON UPDATE CASCADE, Comment VARCHAR, Valid BOOLEAN DEFAULT (1));

-- 表：ICCard
CREATE TABLE ICCard (AutoNo INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, Id VARCHAR NOT NULL UNIQUE, CustomerId INTEGER REFERENCES Customer (Id) ON UPDATE CASCADE, GoodsId INTEGER REFERENCES Goods (Id) ON UPDATE CASCADE, CarAutoNo INTEGER REFERENCES Car (AutoNo) ON UPDATE CASCADE, By1 VARCHAR, By2 VARCHAR, By3 VARCHAR, By4 VARCHAR, By5 VARCHAR);

-- 表：Role
CREATE TABLE Role (RoleId INTEGER PRIMARY KEY AUTOINCREMENT, RoleName VARCHAR NOT NULL UNIQUE, RolePermission VARCHAR, Valid BOOLEAN DEFAULT (1));
INSERT INTO Role (RoleId, RoleName, RolePermission, Valid) VALUES (1, '系统管理员', '称重操作,修改磅单样式,数据备份恢复,查询列表,打印列表,导出列表,删除列表,修改选中,删除选中,补打选中,手工制单,查询报表,打印报表,导出报表,用户管理,角色管理,客户管理,车辆管理,物资管理,IC卡管理,系统字段,系统设置,系统日志查询', 1);

-- 表：SyncData
CREATE TABLE SyncData (AutoNo INTEGER PRIMARY KEY AUTOINCREMENT, WeighingRecordBh VARCHAR NOT NULL, SyncMode VARCHAR NOT NULL, SyncStatus BOOLEAN DEFAULT (0) NOT NULL);

-- 表：SysField
CREATE TABLE SysField (AutoNo INTEGER PRIMARY KEY AUTOINCREMENT, FieldType VARCHAR NOT NULL, FieldValue VARCHAR NOT NULL UNIQUE, Valid BOOLEAN DEFAULT (1));
INSERT INTO SysField (AutoNo, FieldType, FieldValue, Valid) VALUES (1, '客户类型', '自定义客户类型1', 1);
INSERT INTO SysField (AutoNo, FieldType, FieldValue, Valid) VALUES (2, '物资类型', '自定义物资类型1', 1);

-- 表：User
CREATE TABLE User (UserId INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, UserName VARCHAR NOT NULL, UserRole VARCHAR REFERENCES Role (RoleName) ON UPDATE CASCADE, LoginId VARCHAR NOT NULL UNIQUE, LoginPwd VARCHAR, Valid BOOLEAN DEFAULT (1));
INSERT INTO User (UserId, UserName, UserRole, LoginId, LoginPwd, Valid) VALUES (1, '系统管理员', '系统管理员', 'admin', 'admin', 1);

-- 表：WeighingRecord
CREATE TABLE WeighingRecord (AutoNo INTEGER PRIMARY KEY AUTOINCREMENT, Bh VARCHAR, Kh VARCHAR, Kh2 VARCHAR, Kh3 VARCHAR, Ch VARCHAR, Wz VARCHAR, Mz VARCHAR, Mzrq VARCHAR, Mzsby VARCHAR, Pz VARCHAR, Pzrq VARCHAR, Pzsby VARCHAR, Jz VARCHAR, Jzrq VARCHAR, Kz VARCHAR, Kl VARCHAR, Sz VARCHAR, Bz VARCHAR, ICCard VARCHAR, By1 VARCHAR, By2 VARCHAR, By3 VARCHAR, By4 VARCHAR, By5 VARCHAR, WeighingTimes INTEGER, WeighingFormTemplate VARCHAR, IsFinish BOOLEAN DEFAULT (0), Valid BOOLEAN DEFAULT (1));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
